spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/dekairr;DB_CLOSE_DELAY=-1
    username: ""
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, h2, faker
  h2:
    console.enabled: true
server:
  port: 8088

logging:
  level:
    ROOT: DEBUG
    com.dk: DEBUG
    org.hibernate.SQL: DEBUG
    com.mycompany.myapp: DEBUG