spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rr?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.generate_statistics: false
      hibernate.format_sql: false


  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, h2, faker
server:
  port: 8088

logging:
  level:
    ROOT: DEBUG
    com.dk: DEBUG
    org:
      hibernate:
        SQL: DEBUG
    com.mycompany.myapp: DEBUG

rrconig:
  security:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: NzBjOWZkN2U5MmE5ZjJmY2NiZThhNmI5ODFkZjE2YjYwNzNiZjRkNjk1OGIxNDEyZDVjYzFiYmVhYzc1NTlkZmQ1YWRmYTc5MTY3MGVhNjM2MjMwNGY3NmY4OGZlMjA4MTdiZGMyOGIyOWYyMzNkY2Y3ZGIzOTdiMmVkOGJkNGU=
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000
